[package]
name = "instruction-creator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["proc-macro"]

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"

[dependencies.syn]
version = "2.0.77"
features = ["full"]
